# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: 9205
  servlet:
    # 应用的访问路径
    context-path: /flowable-ui
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # tomcat最大线程数，默认为200
    #max-threads: 800
    # Tomcat启动初始化的线程数，默认值25
    #min-spare-threads: 30
flowable:
  customMybatisXMLMappers:
    - mappers/CustomMybatisXmlMapper.xml
  customMybatisMappers:
    - com.dromara.flow.ui.mapper.CustomMybatisMapper
--- # Actuator 监控端点的配置项
management:
  health:
    ldap:
      enabled: false
    mail:
      enabled: false
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
    logfile:
      external-file: ./logs/ruoyi-flow-ui.log
spring:
  profiles:
    active: @profiles.active@
