--- # 监控配置
spring.boot.admin.client:
  # 增加客户端开关
  enabled: true
  # 设置 Spring Boot Admin Server 地址
  url: http://localhost:9090/admin
  instance:
    service-host-type: IP
  username: ruoyi
  password: 123456
# Spring配置
spring:
  application:
    name: flow-ui
  main:
    allow-bean-definition-overriding: true
  liquibase:
    enabled: false
#  jackson:
#    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n/messages
  datasource:
    url: jdbc:mysql://localhost:3306/ry-vue?zeroDateTimeBehavior=convertToNull&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false&nullCatalogMeansCurrent=true
    username: root
    password: 123456
flowable:
  databaseSchemaUpdate: true
#  databaseSchema:

# 日志配置
logging:
  level:
    org.flowable.engine.impl.persistence.entity.*: DEBUG
    org.flowable.task.service.impl.persistence.entity.*: DEBUG # 日志配置
